"""Favorite movies2

Revision ID: 70443b0eadc2
Revises: 2506346c6c83
Create Date: 2024-11-04 13:30:09.226211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70443b0eadc2'
down_revision: Union[str, None] = '2506346c6c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_movies_favorite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_movies_id_movies_favorite'), 'favorite_movies', ['id_movies_favorite'], unique=False)
    op.create_index(op.f('ix_favorite_movies_id_user'), 'favorite_movies', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_movies_id_user'), table_name='favorite_movies')
    op.drop_index(op.f('ix_favorite_movies_id_movies_favorite'), table_name='favorite_movies')
    op.drop_table('favorite_movies')
    # ### end Alembic commands ###
