"""data_movies

Revision ID: 7190eb256f41
Revises: 70443b0eadc2
Create Date: 2024-11-05 09:27:09.877095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7190eb256f41"
down_revision: Union[str, None] = "70443b0eadc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("favorite_movies", sa.Column("data_movies", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorite_movies_data_movies"), table_name="favorite_movies")
    op.drop_column("favorite_movies", "data_movies")
    # ### end Alembic commands ###
