"""Add user model2

Revision ID: b7ff7b60254b
Revises: bde6ced9ec47
Create Date: 2024-08-30 13:16:04.821885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7ff7b60254b"
down_revision: Union[str, None] = "bde6ced9ec47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "given_name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "users",
        "family_name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "family_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "users",
        "given_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
